### DO NOT EDIT THIS FILE ###
export DEFCONFIG_DIR     := configs
export DOCKER_DIR        := configs/docker
export OE_INIT_BUILD_ENV := platform/poky/oe-init-build-env

include platform/wizard/main.mk
### DO NOT EDIT THIS FILE ###
