### DO NOT EDIT THIS FILE ###
export OB_TYPE              := yocto
export OB_DEFCONFIG_DIR     := ${CURDIR}/configs
export OB_DOCKER_DIR        := ${CURDIR}/configs/docker
export OB_BB_INIT_BUILD_ENV := ${CURDIR}/platform/poky/oe-init-build-env

include platform/openbar/main.mk
### DO NOT EDIT THIS FILE ###
