### DO NOT EDIT THIS FILE ###
export DEFCONFIG_DIR     := ${CURDIR}/configs
export DOCKER_DIR        := ${CURDIR}/configs/docker
export OE_INIT_BUILD_ENV := ${CURDIR}/platform/poky/oe-init-build-env

include platform/openbar/main.mk
### DO NOT EDIT THIS FILE ###
