export OB_TYPE := initenv
export OB_DEFCONFIG_DIR := ${CURDIR}/../../../tests/data
export OB_CONTAINER_DIR := ${CURDIR}/../../../tests/data/container
export OB_INITENV_SCRIPT := ${CURDIR}/../../../tests/data/initenv

include ${CURDIR}/../../../core/main.mk
